name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5

      - name: 'Build Lambda ZIP'
        run: |
          cd lambda
          chmod +x build.sh  
          ./build.sh         

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./api_gateway

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: ./api_gateway

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: ./api_gateway
        env:
          TF_LOG: DEBUG
